name: Publish Snapshots

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'src/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        needs: []
        permissions:
            contents: read
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Publish Beta
              run: bun run publish:snapshot
              env:
                  NPM_TOKEN: ${{ secrets.NPM_SECRET }}